### PR TITLE
Added Narcotics RFC

### PR DESCRIPTION
**Pull request by tommykent1210**
Also fixed an instance of baseurl=>safebaseurl

### CODE REVIEW

**Comment by Destroy666x** [comment]
Can't merge it

**Comment by JoshHarmon** [comment]
Oh Tom... You didn't pull before editing. I fixed the safebaseurl that you did.

**Comment by tommykent1210** [comment]
Oops my bad xD Because it was a single edit I did it through the website. I have no idea how I make that do a pull :/

**Comment by JoshHarmon** [comment]
Then I have no idea how a conflict arose. :D

**Pull request closed without merging**
