### PR TITLE
Add Support eligibility page

### PR DESCRIPTION
**Pull request by Sama34**

### CODE REVIEW

**Comment by JordanMussi** [comment]
Shouldn't this page be under [support](http://www.mybb.com/support/)?

**Comment by Destroy666x** [comment]
@JordanMussi, where is that page accessible from though? Can't find any links to /support.

**Comment by pkill37** [comment]
Yeah, I would add it under the support pages too.

However, there is no support folder, so you'll have to create it and rename `support.html` to `support/index.html`. Then create `support/eligibility-policy.html` with the contents of the Support Eligibility Policy.

**Comment by pkill37** [comment]
@Destroy666x It's linked to from the footer.

**Comment by Destroy666x** [comment]
Oh ok. I agree too then.

**Comment by Sama34** [comment]
Not sure, this is quite an important page that I think it should be on its own.

Do users already read the support page ? I doubt it. I think they simply go straight to the community forums. So we need a page to point directly about our policy.

But I understand the logic to put it there, so lets just wait for more feedback.

**Comment by JordanMussi** [comment]
I agree it should be highly visible, so we should add a notice when a thread is being created in a MySupport forum to make users looks at it. Also possibly add it into the license agreement stage on install.
However it is better placed as a sub page of support.

**Comment by Destroy666x** [comment]
So what's the consensus? I personally think it should be under Support and the MySupport notice idea isn't bad either.

**Comment by euantorano** [comment]
I agree, it should be under support.

**Comment by JoshHarmon** [comment]
Closing as #21 is more toward what we want (and I didn't pull this down successfully for some reason??).

**Pull request closed without merging**
