### PR TITLE
Add YouTube subscribe button

### PR DESCRIPTION
**Pull request by JoshHarmon**
Modifies:
- _includes/social_buttons.html   to add a div for YouTube button styling at the bottom
- assets/css/screen.css               to align the button a bit better
- assets/css/screen.min.css        to align the button a bit better (but minified!)

Any feedback before making this change live?

### CODE REVIEW

**Comment by Destroy666x** [comment]
Looks ok, but is it just me or the FB like button is cut off on the 1st likes number digit due to most likely `overflow: hidden`? Shouldn't be the case

**Comment by JoshHarmon** [comment]
@Destroy666x I don't see any issue in FF 40, Chrome (Canary), or Safari.

**Comment by Destroy666x** [comment]
What's your screen resolution? It looks like this for me on my 1280x1028 screen:

**Comment by JoshHarmon** [comment]
Errm… 2560x1440 xD

I tested with Firefox’s Responsive Design tools: http://puu.sh/iQnYz/7ca49c71b1.png http://puu.sh/iQnYz/7ca49c71b1.png

**Comment by JN-Jones** [comment]
@Destroy666x You're testing on the current website, aren't you? I've the same problem there. Can't test this PR as I don't have a local installation though.

**Comment by Destroy666x** [comment]
I tested it with the patch, but same thing happens without it, yes.

**Comment by JoshHarmon** [comment]
Yep, I'm on the latest. Pulled from the repo yesterday afternoon and a quick `git pull` shows I'm up to date with origin.

**Comment by JN-Jones** [comment]
Probably related to the language then? @JoshHarmon is the only one using the english version and from a quick look the width is hardcoded. And "Gefällt mir" is longer than "Like"

**Comment by Destroy666x** [comment]
Might be

**Comment by Sama34** [comment]
https://stackoverflow.com/questions/4348235/how-can-i-make-the-facebook-like-buttons-width-automatically-resize

**Comment by JoshHarmon** [comment]
Ditching this because I don't want to deal with fixing those buttons.

**Pull request closed without merging**
