### PR TITLE
Adds MD5 below the download button

### PR DESCRIPTION
**Pull request by JoshHarmon**
In software distribution, it's become pretty common for checksums to be displayed on download pages. This PR adds an MD5 key to the MyBB _data files and drops it under the download button on the download page.

This also tweaks the CSS for the previous release downloadBit, increasing the width a tad so that the MD5 will display on one line. I also increased the padding on the button to 60 to fill the new space created.

I have not done this for the merge system yet, so perhaps I'll do that before this potentially gets accepted.
Edit: Merge System page -- DONE

Feedback?

### CODE REVIEW

**Comment by Sama34** [comment]
What is up with the merge system zip file?

**Comment by JoshHarmon** [comment]
@Sama34 - good question. Must have accidentally downloaded it when I was in the directory. I'll remove it later today.

**Comment by JoshHarmon** [comment]
@Sama34 Zip file has been removed. This PR is ready for conflict resolution!

**Comment by Sama34** [comment]
Wouldn't you to fix the conflict? :P

**Comment by JoshHarmon** [comment]
Agh, I guess I can do that later :P

**Comment by JoshHarmon** [comment]
Closing this as it's caused half the repo to conflict, it seems. Will redo without the git mess that currently exists.

**Pull request closed without merging**
