### PR TITLE
Add Version Check

### PR DESCRIPTION
**Pull request by JordanMussi**
The `_layouts/blank.html` file isn't necessary I added it incase a blank layout was wanted.

### CODE REVIEW

**Comment by justinsoltesz** [comment]
I'm not entirely certain if the version check will change going forward, but this seems like a good way to handle it, so I'm going to go ahead and merge it now. We can always change it later if necessary.

**Comment by pkill37** [comment]
What's the `version_check.php` file for?

**Comment by JordanMussi** [comment]
Because the software currently checks `www.mybb.com/version_check.php` for version information. I included it for backwards compatibility (i.e. so that previous versions can still tell that they are out of date).

**Comment by nmalcolm** [comment]
It makes sense to keep it there and update it until 1.x is no longer supported. There are some other scripts on the server which still need to be on our server (and rewritten, too) so we'll probably have to setup a subdomain for them and somehow redirect them.

**Pull request merged**
