### PR TITLE
Denote Language Translations for MyBB Version

### PR DESCRIPTION
**Pull request by JordanMussi**
This makes the MyBB version of a translation bold if it is made for the latest version of MyBB.

### CODE REVIEW

**Comment by Stefan-MyBB** [comment]
Note: Some versions don't change anything related to translations. In that case translations for the previous version(s) work as well (translators probably won't release a new version).

**Comment by JordanMussi** [comment]
Hmm, that's a good point. I didn't think about that.

**Comment by JordanMussi** [comment]
@Stefan-ST, if there was a variable in the latest_mybb data file, called lang_update (or similar) and is set to the last MyBB version that included changes to language files and then compared to that, would that approach be OK?

_data/latest_mybb.yml (excerpt):`lang_update: 1612`
download/translations.html (excerpt): `{% if translation.version >= site.data.latest_mybb.lang_update %}`

**Comment by JN-Jones** [comment]
That should work, probably leave it empty to use the normal mybb version? Not sure about this.

**Comment by JordanMussi** [comment]
That sounds better. So the logic would be: `{% if (site.data.latest_mybb.lang_update == '' and translation.version == site.data.latest_mybb.version) or translation.version >= site.data.latest_mybb.lang_update %}`

I'm currently unsure what liquid uses for its or & and statements: `OR`, `or` or `||` & `AND`, `and` or `&&`

**Comment by pkill37** [comment]
Even if there are no changes to language files I would argue translations should be "updated" to imply that they work with the current MyBB version.

If that's not how it currently works, maybe it should be.

**Comment by JordanMussi** [comment]
That's what I was going with in the initial changes in the pull request. :wink: At the moment I think bumping the language version number is best.

**Comment by pkill37** [comment]
Why? It introduces more steps in releasing a new version and it isn't explicit for end users when downloading translations.

The whole translations thing is already going to change in 1.8. We might as well introduce a new rule that forces translators to verify that their translation works with the latest version, and make a new release based on that.

**Comment by JordanMussi** [comment]
I don't think I made myself that clear looking back. :blush: I meant that the language _pack_ version number should be bumped.

**Comment by JordanMussi** [comment]
Translations are now listed on the Mods Site: http://community.mybb.com/mods.php?action=browse&category=19

**Pull request closed without merging**
