### PR TITLE
Create security.txt

### PR DESCRIPTION
**Pull request by JordanMussi**
Adds `security.txt` ([current draft](https://tools.ietf.org/html/draft-foudil-securitytxt-02))

### CODE REVIEW

**Comment by euantorano** [comment]
It may be worth noting that the hall of fame isn't currently active. it was planned to be implemented for 2.0, but since we're postponing that it'll likely be introduced with 1.9 - ping @dvz for thoughts.

**Comment by JordanMussi** [comment]
Fixed conflicts and updated to [draft 09](https://tools.ietf.org/html/draft-foudil-securitytxt-09).

**Comment by dvz** [comment]
Looks like Jekyll doesn't parse variables in `.txt` files (it may be also a good idea to use hardcoded URLs for sensitive locations like Policy and Encryption).

**Comment by JordanMussi** [comment]
Ooops that's my mistake copying from the old code!

It works if it has the header at the top:
```
---
---
# Security contact email
Contact: mailto:security@mybb.com
# Contact MyBB Group via Private Inquiries forum
Contact: https://community.mybb.com/forum-135.html

# When contacting an individual team member use their public key
Encryption: {{ site.mainsiteurl }}/about/team/

# Information on responsible disclosure
Policy: {{ site.mainsiteurl }}/get-involved/security/

# Security Hall Of Fame
Acknowledgments: {{ site.mainsiteurl }}/get-involved/security/hall-of-fame/

Canonical: {{ site.mainsiteurl }}/.well-known/security.txt
```

**Pull request merged**
