### PR TITLE
Fixes mybb/docs.mybb.com#48 Consistently style 404.html file

### LINKED ISSUE #48: Consistently style 404.html file
On the main website the 404 file seems to display correctly, but not on the documentation.
http://www.mybb.com/foo
http://docs.mybb.com/foo

### PR DESCRIPTION
**Pull request by JordanMussi**
Fixes mybb/docs.mybb.com#48 Consistently style 404.html file

### CODE REVIEW

**Comment by Destroy666x** [comment]
@JoshHarmon, any reason why this wasn't closed after another patch had been applied?

**Comment by JoshHarmon** [comment]
Are you talking about the one I just approved on docs.mybb.com? If so, I wasn't aware that this one existed.

**Comment by JoshHarmon** [comment]
Closing as docs and this match and are styled appropriately now, from what I can tell.

**Comment by JordanMussi** [comment]
This Pull Request still needs to be merged.
The title on the MyBB website is currently: `404`
The title on the MyBB Documentation is currently: `404 - File Not Found`

**Comment by JoshHarmon** [comment]
Oh my! I'll take a look at that!

**Comment by JoshHarmon** [comment]
Will verify the fix later when I get to an unfiltered network (home), unless someone does it sooner.

I didn't merge this originally because the markup looked considerably different whilst the PR was supposed to make them look the same.

**Pull request merged**
