### PR TITLE
No underscore in 1st level HTML tags !

### PR DESCRIPTION
**Pull request by cronlabspl**

### CODE REVIEW

**Comment by euantorano** [comment]
This is an XML file rather than HTML, and this would be a breaking change.

**Comment by cronlabspl** [comment]
> This is an XML file rather than HTML, and this would be a breaking change.
> […](#)

No it would not be breaking ( of course provided that you do know what you are doing )

**Comment by euantorano** [comment]
> > This is an XML file rather than HTML, and this would be a breaking change.
> > […](#)
> 
> No it would not be breaking ( of course provided that you do know what you are doing )

Yes, it would. 

This file is used by the merge system to check that it is the current version. If the XML structure is changed here, the code in the merge system has to be changed to use the new tag. The code in question is here: https://github.com/mybb/merge-system/blob/e7619110bde56faf26cec280f4eaeeaec3ec14bf/index.php#L608

You cannot arbitrarily change XML tags that are used elsewhere without changing the code everywhere else they are used.

**Comment by cronlabspl** [comment]
No it would not.

Will try and send chunked PR

**Pull request closed without merging**
