### PR TITLE
MyBB website redesign

### PR DESCRIPTION
**Pull request by justinsoltesz**
**THIS IS NOT READY TO MERGE** and should not be merged until the entire new site is ready for launch.

This includes all of the changes to move the new site over to the primary mybb.com repo.

Looks like there are some conflicts that need to be resolved before this can be merged as well, which I'll look at soon.

### CODE REVIEW

**Comment by JordanMussi** [comment]
There isn't a `get-involved/discord.html` file in mybb/wip.mybb.com so deleting the file (and the `get-involved/discord/rules.html`) might be the way to fix the conflict.

**Comment by justinsoltesz** [comment]
The files should be there. It just needs to be updated to match the changes
that were just made to that file.

**Comment by justinsoltesz** [comment]
Fixed the merge conflicts in `discord.html`.

Note: I still need to update `_config.yml` before this can be merged. (`baseurl` needs to be set to blank instead of `/mybb.com`

**Comment by justinsoltesz** [comment]
Ready to go!

**Comment by justinsoltesz** [comment]
Closing this as it appears #100 has resolved the conflicts.

**Pull request closed without merging**
